[bumpversion]
current_version = 1.4.0
commit = True
tag = True

[metadata]
name = j2render
version = attr: j2render.__version__
description = Render Jinja2 templates from the command line
long-description = file: README.md
long-description-content-type = text/markdown
url = https://github.com/fredrikhl/jinja2-render
author = fredrikhl
license = MIT
classifiers = 
	Development Status :: 3 - Alpha
	Environment :: Console
	Programming Language :: Python :: 3
	Programming Language :: Python

[options]
include_package_data = True
packages = find:
package_dir = 
	= src/
install_requires = 
	Jinja2 ~= 3.1
	PyYAML ~= 6.0

[options.packages.find]
where = src
include = 
	j2render

[options.entry_points]
console_scripts = 
	j2render = j2render:main

[options.extras_require]
dev = 
	build
	bump2version

[bdist_wheel]
universal = 1

[bumpversion:file:src/j2render.py]

